# Generated by Django 3.2.22 on 2023-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('subject', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('data_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
